version: "3.9"

services:
  django-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
  
  